# A sample Guardfile
# More info at https://github.com/guard/guard#readme

# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }
#
guard :shell, :all_on_start => true do
  watch(/final_report\.tex/) do |m| 
      puts "="*100
      `make final_report.pdf`
  end
end
